### PR TITLE
Fixed the issues: editor fonts and sorting notes #156 and Search by date attributes not working with PPA builds #149

### PR DESCRIPTION
**Pull request by boo-yee**
The original issue link is https://github.com/robert7/nixnote2/issues/156 and https://github.com/robert7/nixnote2/issues/149.

The font size can be changed in most of the time, but not always. When the font size is set to some specific value such as 10pt, it may become the start of problems. This issue is caused by the html tag auto completion of QWebview. QWebview intends to complete the html tags for the users, but it may make troubles sometimes. After selecting font size as 10pt, and removing the text, when input a character again, QWebview will add a font tag with 'size' attribute set, but it cannot deal with this attribute correctly if the users change the font size again. I just replaced the 'size' attribute with 'font-size' attribute with JS.

This issue can be reproduced like this (it may be a little tedious if I describe it in text, so I upload several pictures):

issue156_text

And there are problems when changing the font size in blockquote, unordered list, table, etc, it will break the original format.

issue156_bq

issue156_list

After fixing it, it is like:

issue156_fixed_text

issue156_fixed_bq

issue156_fixed_list

In addition to this issue, I also added a functionality that the font size can be changed when no text is selected.

As to the sort function, I copied the sort code from the original code repository. This may be useful for some users.

And I added the word-wrap attribute to the note template. Without it, the horizontal scrollbar will appear when the line exceeds the editor width. I noticed that it was removed by someone. If you know the reason, please tell me.

Issue 149 is caused by the sqlite datetime function not executed correctly. Actually there is no need to call it when comparing two datetime variable values, so I just removed it and compared the seconds since epoch directly, and it works fine now.

### CODE REVIEW

**Comment by robert7** [comment]
looks great! thanks again!

just please also update the CHANGELOG file (the file is checked in at 2 places - /changelo.txt and in /debian/changelog - update one of them and then copy it to other location - sorry I don't remember anymore, why 2 copies are needed - but there was some reason :) )

then I can merge it.

**Comment by boo-yee** [comment]
> NixNote (2.1.7) stable; urgency=low
  * Fixed: Editor fonts and sorting notes - issue #156
  * Fixed: Search by date attributes not working with PPA builds - issue #149
  * Fixed: Nixnote often crashes automatically.
  * Fixed: Can't search / replace with as replacement. - issue #180
  * Enabled the spell check code for Windows edition
  * Fixed Windows build (thanks to https://github.com/boo-yee)
 -- Robert Spiegel <nightingale7@gmail.com>  Tue, 17 May 2022 10:00:00 +0200

Write like this? Is it OK ?

But then again, should we notify the people who raised these issues first that their issues have been fixed ?

**Comment by robert7** [comment]
>Write like this? Is it OK ?

yes that's perfect. thanks

>But then again, should we notify the people who raised these issues first that their issues have been fixed ?
if you use the ticket number in comments, they should got a notification

but you are welcome also to write some more info in the relevant tickets

**Comment by robert7** [comment]
you can also close fixed tickets

**Comment by boo-yee** [comment]
I have updated the changelog files. And earlier today, I fixed another small bug, you may want to review it by the way. Thanks.

**Comment by robert7** [comment]
OK thanks!!

**Pull request merged**
