### PR TITLE
Feature: Open note from URL

### PR DESCRIPTION
**Pull request by rodelrod**
Added the following options to `nixnote2 signalGui`:

- `--openNoteUrl`
- `--openExternalNoteUrl`
- `--openNoteNewTabUrl`

They all require a `--url` parameter which should contain an in-app or external Note URL

E.g.: 

```bash
nixnote2 signalGui --openNoteNewTabUrl --url=evernote:///view/1234567/s24/2d49fb1b-1897-a014-d26b-7292646e02bf/2d49fb1b-1897-a014-d26b-7292646e02bf/
```

### CODE REVIEW

**Comment by robert7** [comment]
hey!
I looked at it and it looks good..
But I did some sample test and it someway did not worked... I tried `nixnote2 signalGui --logLevel=1 --openNoteUrl --url=evernote:///view/189781677/s716/1d1b83e1-5a70-470a-978f-e408247b86a2/1d1b83e1-5a70-470a-978f-e408247b86a2/` but the note was not opened..
The other instance wrote something like
```
INFO  2020-03-10 21:23:10.377 src/nixnote.cpp:2730 SIGNAL_GUI requested by shared memory segment.
DEBUG 2020-03-10 21:23:10.377 src/nixnote.cpp:2732 COMMAND REQUESTED: "OPEN_NOTE 0"
```

Could you please add some more debug statements? To better see, where it goes wrong?
Unfortunately my debugging abilities are now limited, as I'm on macOS now and can't yet compile it on Mac. I can only compile it now in VM. But I'm working on it... as far as time allows.

**Comment by rodelrod** [comment]
Let me check. I'm only using `--openExternalNoteUrl` and since I didn't add any tests I may have messed up `--openNoteUrl` when I added the other options.

**Comment by rodelrod** [comment]
I pushed a fix, it's now working for me for the 3 commands. Sorry for the time waste!

**Comment by robert7** [comment]
No problem, I'll recheck later. Thx!

**Comment by robert7** [comment]
OK, its seems to work, but fort the `--openNoteUrl`, the selection is not updated.. so its confusing
image

I will merge anyway, but you could improve, if you have time

**Comment by robert7** [comment]
note I merged so far to my feature branch; i'll update the changelog, then merge it to develop branch
then you can install from nixnotre-develop PPA or user development AppImage to check

**Comment by rodelrod** [comment]
Hi Robert, thanks for merging!
> for the --openNoteUrl, the selection is not updated.. so its confusing

I know, that's one of the main reasons I don't use it. 

Unfortunately the bug was already there. That's the behaviour of the original `--openNote`. 

Since it touches the UI it goes well beyond what I could fix easily.

**Comment by robert7** [comment]
Hi Rodrigo,
OK. I merged the changes to develop. The AppImage build is running, the PPA will be updated later today. Thanks for the PR!!

**Comment by robert7** [comment]
I will merge the changes to master later..

**Pull request merged**
