### PR TITLE
Fix issue 222: API Issues with initial sync (RateLimitExceeded)

### PR DESCRIPTION
**Pull request by boo-yee**
Synchronize the notes with five threads, it used single thread before. And catch the std::exception thrown from processSyncChunk() and deal with it properly to make the sync button stop when the connection is closed(by the server or by other network exceptions).

### CODE REVIEW

**Comment by boo-yee** [comment]
@robert7 Hi, Robert. It seems that the Travis CI stopped working again. Could you please check it and build a new release with it?

**Comment by boo-yee** [comment]
@robert7 Hi, Robert. It seems that the Travis CI stopped working again. Could you please check it and build a new release with it?

**Comment by boo-yee** [comment]
@robert7 Hi, Robert. It seems that the Travis CI stopped working again. Could you please check it and build a new release with it?

**Comment by robert7** [comment]
I reached to Travis already on Saturday. It should work now. I retriggered build for develop branch.

**Comment by boo-yee** [comment]
I see the new release. Thanks again.

**Comment by robert7** [comment]
Unfortunately, this will fail again in the future, as I only got some free "build tokens" for open-source builds and they either run out or expire eventually and I need to ask Travis again. But they usually response quite quickly and resolve the issue.

**Comment by boo-yee** [comment]
OK, got it. It seems that we have to call Travis CI as less as possible.

**Comment by robert7** [comment]
> we have to call Travis CI as less as possible

~yes, but it is not a big problem to renew it. If it gets broken, I"ll just write them again 😀
No problem.

**Comment by vitaly-zdanevich** [comment]
Maybe switch CI to GitHub Actions, if Travis have some problems?

**Comment by robert7** [comment]
yes, if you can rewrite the script, as unfortunately, I don't have time to do it

**Pull request merged**
