### PR TITLE
Comment out the tedious resource synchronization code.

### PR DESCRIPTION
**Pull request by boo-yee**
Hi, Robert. The rate limit excpetion was often talked about earlier. Maybe we can have an improvement now.

I found that Nixnote sychronizes the resources twice, when syncing the notes, the resources are synced together in fact, but it seems that Nixnote syncs the resources one by one later, and I think this is the reason that the exception often appears. So I commented out the standalone resources sychronization code. I commented out instead of deleting them, because I am afraid that there are some side effects. I have tested with an account which has only a few notes and resources, and the notes can be synchronized normally, but I am not totally sure if the exception occurs when there are a large amount of notes.

It cannot walk around the limit totally, but it should possibly low down its occurrence. My trouble now is that I find it takes too much time to upload my faked large sized note content, so I hope someone who has a large amount of notes can help on it, if there is any. So please use the travis CI to build a binary file if possible for the convenience of testing. Thank you first.

For solving this issue, I referred to the code of evernote-back(an open source project too, for backuping up notes, rate limit excepton lessly happens on it), and found it syncs the note along with the resources, no standalone synchronization for the resources. That is to say, if there are 1k notes, each note contains two images, then Nixnote previously needed to make (a few more than)1k+2k api callings. If we sync the notes together with the resources, it will be only (a few more than)1k. Based on this estimation, I think we can reduce the rate limit exceptons.

I keep the changelog unchanged for now. I'll update it as soon as the testing is finished.

### CODE REVIEW

**Comment by boo-yee** [comment]
Sorry but I have not completed yet, maybe have to work for more time. :(

**Comment by boo-yee** [comment]
I have updated the post, adding some details, and I think you could check the changes now.

**Comment by robert7** [comment]
Hi,
I can't test the changes myself now, but it looks good, and I merged your changes to develop.

Unfortunately Travis build doesn't work now, as my free account expired, but I already wrote to Travis, hopefully the resume my account.
Robert

**Comment by boo-yee** [comment]
That's all right. We can still do it by ourselves.

**Comment by boo-yee** [comment]
There is a parameter of getNote function called withResource. If it is set to true, the api caller will download the reource along with the note. that is why I think the commented out code is tedious.

**Comment by boo-yee** [comment]
It seems that the Travis CI works now and the latest AppImage has been built. Thanks again.

**Comment by robert7** [comment]
Travis account is renewed and should work until end of 2024 (then it would need another renew)

**Pull request merged**
